./remake.sh bcftools
./remake.sh bcl2fastq
./remake.sh bedtools
./remake.sh bowtie2
./remake.sh bwa
./remake.sh cat
./remake.sh cp
./remake.sh cellranger
./remake.sh cutadapt
./remake.sh deseq2
./remake.sh echo
./remake.sh fastqc
./remake.sh gunzip
./remake.sh gzip
./remake.sh ls
./remake.sh macs2
./remake.sh mpileup
./remake.sh qorts
./remake.sh rnaseqc
./remake.sh samtools
./remake.sh seurat
./remake.sh star
./remake.sh tar
./remake.sh varscan2
./remake.sh zcat
